//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Config.i18n.Ressources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources_en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Job.Config.i18n.Resources.Resources.en", typeof(Resources_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Business App.
        /// </summary>
        internal static string AddBusinessAppWatermark {
            get {
                return ResourceManager.GetString("AddBusinessAppWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string AddButton {
            get {
                return ResourceManager.GetString("AddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File extension added successfully.
        /// </summary>
        internal static string AddFileExtension {
            get {
                return ResourceManager.GetString("AddFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add File Type.
        /// </summary>
        internal static string AddFileTypeWatermark {
            get {
                return ResourceManager.GetString("AddFileTypeWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad arguments, require Add-Savejob &lt;name&gt; &lt;source&gt; &lt;destination&gt; &lt;type&gt;.
        /// </summary>
        internal static string AddSjBadArgs {
            get {
                return ResourceManager.GetString("AddSjBadArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to real type are full | diff.
        /// </summary>
        internal static string AddSJBadType {
            get {
                return ResourceManager.GetString("AddSJBadType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad arguments given :.
        /// </summary>
        internal static string BadArgsGiven {
            get {
                return ResourceManager.GetString("BadArgsGiven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse....
        /// </summary>
        internal static string BrowseButton {
            get {
                return ResourceManager.GetString("BrowseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Applications Blocking SJ.
        /// </summary>
        internal static string BusinessAppBlockingTitle {
            get {
                return ResourceManager.GetString("BusinessAppBlockingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The business app already exists.
        /// </summary>
        internal static string BusinessAppExists {
            get {
                return ResourceManager.GetString("BusinessAppExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business app running, execution locked.
        /// </summary>
        internal static string BusinessAppLock {
            get {
                return ResourceManager.GetString("BusinessAppLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is call with args : .
        /// </summary>
        internal static string CallWithArgs {
            get {
                return ResourceManager.GetString("CallWithArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created : .
        /// </summary>
        internal static string Created {
            get {
                return ResourceManager.GetString("Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation.
        /// </summary>
        internal static string Creation {
            get {
                return ResourceManager.GetString("Creation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletation of file extension.
        /// </summary>
        internal static string DelFileExtension {
            get {
                return ResourceManager.GetString("DelFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad arguments, require Delete-SaveJob &lt;id&gt;.
        /// </summary>
        internal static string DelSjBadArgs {
            get {
                return ResourceManager.GetString("DelSjBadArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete-SaveJob : is call with args :.
        /// </summary>
        internal static string DelSjCallWithArgs {
            get {
                return ResourceManager.GetString("DelSjCallWithArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination :.
        /// </summary>
        internal static string Destination {
            get {
                return ResourceManager.GetString("Destination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination path.
        /// </summary>
        internal static string DestPath {
            get {
                return ResourceManager.GetString("DestPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Differential.
        /// </summary>
        internal static string Differential {
            get {
                return ResourceManager.GetString("Differential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination directory does not exist.
        /// </summary>
        internal static string DstDirNotExist {
            get {
                return ResourceManager.GetString("DstDirNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file is already tracked.
        /// </summary>
        internal static string EncryptFileExists {
            get {
                return ResourceManager.GetString("EncryptFileExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Encryption Key.
        /// </summary>
        internal static string EnterEncryptionKeyWatermark {
            get {
                return ResourceManager.GetString("EnterEncryptionKeyWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad arguments, require Exec-Savejob &lt;id&gt;|&lt;name&gt; or &lt;id&gt;;&lt;id&gt;;&lt;id&gt; or &lt;id&gt;,&lt;id&gt; .
        /// </summary>
        internal static string ExecSjBadArgs {
            get {
                return ResourceManager.GetString("ExecSjBadArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute.
        /// </summary>
        internal static string Execute {
            get {
                return ResourceManager.GetString("Execute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The extension already exists.
        /// </summary>
        internal static string FileExtensionExists {
            get {
                return ResourceManager.GetString("FileExtensionExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prioritary file type.
        /// </summary>
        internal static string FilePriority {
            get {
                return ResourceManager.GetString("FilePriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Types to Encrypt.
        /// </summary>
        internal static string FileTypesToEncryptTitle {
            get {
                return ResourceManager.GetString("FileTypesToEncryptTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full.
        /// </summary>
        internal static string Full {
            get {
                return ResourceManager.GetString("Full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id : .
        /// </summary>
        internal static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The id should be a number .
        /// </summary>
        internal static string IdShouldBeANumber {
            get {
                return ResourceManager.GetString("IdShouldBeANumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid type : .
        /// </summary>
        internal static string InvalidType {
            get {
                return ResourceManager.GetString("InvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad arguments, require en or fr : .
        /// </summary>
        internal static string LanguageBadArgs {
            get {
                return ResourceManager.GetString("LanguageBadArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language changed to : .
        /// </summary>
        internal static string LanguageChanged {
            get {
                return ResourceManager.GetString("LanguageChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this language is not supported, require en or fr.
        /// </summary>
        internal static string LanguageNotSupported {
            get {
                return ResourceManager.GetString("LanguageNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Execution.
        /// </summary>
        internal static string LastExecution {
            get {
                return ResourceManager.GetString("LastExecution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last save :.
        /// </summary>
        internal static string LastSave {
            get {
                return ResourceManager.GetString("LastSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List-SaveJob : is call with args : .
        /// </summary>
        internal static string ListSjCallWith {
            get {
                return ResourceManager.GetString("ListSjCallWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad arguments, require Set-LogPath &lt;logPath&gt;.
        /// </summary>
        internal static string LogPathBadArgs {
            get {
                return ResourceManager.GetString("LogPathBadArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogPath has been updated : .
        /// </summary>
        internal static string LogPathUpdatedSuccesfully {
            get {
                return ResourceManager.GetString("LogPathUpdatedSuccesfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file size limit on parallelized transfert has been updated.
        /// </summary>
        internal static string MaxFileSizeModified {
            get {
                return ResourceManager.GetString("MaxFileSizeModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ex : 4096.
        /// </summary>
        internal static string MaxFileSizeWatermark {
            get {
                return ResourceManager.GetString("MaxFileSizeWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing arguments  : .
        /// </summary>
        internal static string MissingArgs {
            get {
                return ResourceManager.GetString("MissingArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name .
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no SaveJob to print.
        /// </summary>
        internal static string NoSjToPrint {
            get {
                return ResourceManager.GetString("NoSjToPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is not a valid path.
        /// </summary>
        internal static string NotValidPath {
            get {
                return ResourceManager.GetString("NotValidPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress.
        /// </summary>
        internal static string Progress {
            get {
                return ResourceManager.GetString("Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Selected.
        /// </summary>
        internal static string RemoveSelectedButton {
            get {
                return ResourceManager.GetString("RemoveSelectedButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string ResetButton {
            get {
                return ResourceManager.GetString("ResetButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume.
        /// </summary>
        internal static string Resume {
            get {
                return ResourceManager.GetString("Resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A save Job already exist with this name.
        /// </summary>
        internal static string SaveAlreadyExist {
            get {
                return ResourceManager.GetString("SaveAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The save jobs are locked by : .
        /// </summary>
        internal static string SaveJobLockBy {
            get {
                return ResourceManager.GetString("SaveJobLockBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Language.
        /// </summary>
        internal static string SelectLanguagePlaceholder {
            get {
                return ResourceManager.GetString("SelectLanguagePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Language.
        /// </summary>
        internal static string SelectLanguageTitle {
            get {
                return ResourceManager.GetString("SelectLanguageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Log Type.
        /// </summary>
        internal static string SelectLogTypePlaceholder {
            get {
                return ResourceManager.GetString("SelectLogTypePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Log Type.
        /// </summary>
        internal static string SelectLogTypeTitle {
            get {
                return ResourceManager.GetString("SelectLogTypeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Save Type.
        /// </summary>
        internal static string SelectSaveType {
            get {
                return ResourceManager.GetString("SelectSaveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Separator not recognized : .
        /// </summary>
        internal static string SeparatorNotReco {
            get {
                return ResourceManager.GetString("SeparatorNotReco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Encryption Key.
        /// </summary>
        internal static string SetEncryptionKeyTitle {
            get {
                return ResourceManager.GetString("SetEncryptionKeyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set-LogPath : is call with args : .
        /// </summary>
        internal static string SetLogPathCallWith {
            get {
                return ResourceManager.GetString("SetLogPathCallWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Log Path.
        /// </summary>
        internal static string SetLogPathTitle {
            get {
                return ResourceManager.GetString("SetLogPathTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Log Path.
        /// </summary>
        internal static string SetLogPathWatermark {
            get {
                return ResourceManager.GetString("SetLogPathWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define files size limit for parallelized transfert.
        /// </summary>
        internal static string SetMaxFileSize {
            get {
                return ResourceManager.GetString("SetMaxFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Job has been created.
        /// </summary>
        internal static string SjCreatedSuccesfully {
            get {
                return ResourceManager.GetString("SjCreatedSuccesfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Jobs deleted :.
        /// </summary>
        internal static string SjDelSuccesfully {
            get {
                return ResourceManager.GetString("SjDelSuccesfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Job done successfully.
        /// </summary>
        internal static string SjExecSuccesfully {
            get {
                return ResourceManager.GetString("SjExecSuccesfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exec-SaveJob : is call with args :.
        /// </summary>
        internal static string SjExecWith {
            get {
                return ResourceManager.GetString("SjExecWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Job does not exist (.
        /// </summary>
        internal static string SjNotExist {
            get {
                return ResourceManager.GetString("SjNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source :.
        /// </summary>
        internal static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source directory does not exist.
        /// </summary>
        internal static string SrcDirNotExists {
            get {
                return ResourceManager.GetString("SrcDirNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source path.
        /// </summary>
        internal static string SrcPath {
            get {
                return ResourceManager.GetString("SrcPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too much id given without separator :.
        /// </summary>
        internal static string TooMuchIdWithoutSep {
            get {
                return ResourceManager.GetString("TooMuchIdWithoutSep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Key.
        /// </summary>
        internal static string UpdateKeyButton {
            get {
                return ResourceManager.GetString("UpdateKeyButton", resourceCulture);
            }
        }
    }
}
