//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Config.i18n.Ressources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources_fr {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_fr() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Job.Config.i18n.Resources.Resources.fr", typeof(Resources_fr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mauvais arguments, Add-Savejob &lt;nom&gt; &lt;source&gt; &lt;destination&gt; &lt;type&gt;.
        /// </summary>
        internal static string AddSjBadArgs {
            get {
                return ResourceManager.GetString("AddSjBadArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  les types possibles sont : full, diff.
        /// </summary>
        internal static string AddSJBadType {
            get {
                return ResourceManager.GetString("AddSJBadType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mauvais arguments donnés :.
        /// </summary>
        internal static string BadArgsGiven {
            get {
                return ResourceManager.GetString("BadArgsGiven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to est appelé avec les arguments : .
        /// </summary>
        internal static string CallWithArgs {
            get {
                return ResourceManager.GetString("CallWithArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créé le : .
        /// </summary>
        internal static string Created {
            get {
                return ResourceManager.GetString("Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mauvais arguments fournis, la commande se formule comme suivant : Delete-SaveJob &lt;id&gt;.
        /// </summary>
        internal static string DelSjBadArgs {
            get {
                return ResourceManager.GetString("DelSjBadArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete-SaveJob : est appelé avec les arguments :.
        /// </summary>
        internal static string DelSjCallWithArgs {
            get {
                return ResourceManager.GetString("DelSjCallWithArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination :.
        /// </summary>
        internal static string Destination {
            get {
                return ResourceManager.GetString("Destination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le répertoire destination n&apos;existe pas.
        /// </summary>
        internal static string DstDirNotExist {
            get {
                return ResourceManager.GetString("DstDirNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mauvais arguments, la commande nécessite Exec-Savejob &lt;id&gt;|&lt;nom&gt; ou &lt;id&gt;;&lt;id&gt;;&lt;id&gt; ou &lt;id&gt;,&lt;id&gt; .
        /// </summary>
        internal static string ExecSjBadArgs {
            get {
                return ResourceManager.GetString("ExecSjBadArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id : .
        /// </summary>
        internal static string Id___ {
            get {
                return ResourceManager.GetString("Id : ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;id doit être un nombre .
        /// </summary>
        internal static string IdShouldBeANumber {
            get {
                return ResourceManager.GetString("IdShouldBeANumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type indisponible.
        /// </summary>
        internal static string InvalidType {
            get {
                return ResourceManager.GetString("InvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mauvais arguments fournis : .
        /// </summary>
        internal static string LanguageBadArgs {
            get {
                return ResourceManager.GetString("LanguageBadArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Langue modifiée au profit de la nouvelle langue : .
        /// </summary>
        internal static string LanguageChanged {
            get {
                return ResourceManager.GetString("LanguageChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to n&apos;est pas un language supporté par le système.
        /// </summary>
        internal static string LanguageNotSupported {
            get {
                return ResourceManager.GetString("LanguageNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dernière sauvegarde : .
        /// </summary>
        internal static string LastSave {
            get {
                return ResourceManager.GetString("LastSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List-SaveJob : est appelé avec les arguments : .
        /// </summary>
        internal static string ListSjCallWith {
            get {
                return ResourceManager.GetString("ListSjCallWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mauvais arguments, la commande nécessite Set-LogPath &lt;logPath&gt;.
        /// </summary>
        internal static string LogPathBadArgs {
            get {
                return ResourceManager.GetString("LogPathBadArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogPath a été mis à jour : .
        /// </summary>
        internal static string LogPathUpdatedSuccesfully {
            get {
                return ResourceManager.GetString("LogPathUpdatedSuccesfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom :.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il n&apos;y a aucun travail de sauvegarde à imprimer.
        /// </summary>
        internal static string NoSjToPrint {
            get {
                return ResourceManager.GetString("NoSjToPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to n&apos;est pas un chemin valide.
        /// </summary>
        internal static string NotValidPath {
            get {
                return ResourceManager.GetString("NotValidPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un travail de sauvegarde existe déjà sous ce nom.
        /// </summary>
        internal static string SaveAlreadyExist {
            get {
                return ResourceManager.GetString("SaveAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les séparateurs sont inconnus du système : .
        /// </summary>
        internal static string SeparatorNotReco {
            get {
                return ResourceManager.GetString("SeparatorNotReco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set-LogPath : est appelé avec les arguments : .
        /// </summary>
        internal static string SetLogPathCallWith {
            get {
                return ResourceManager.GetString("SetLogPathCallWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le nouveau travail de sauvegarde a été sauvegardé.
        /// </summary>
        internal static string SjCreatedSuccesfully {
            get {
                return ResourceManager.GetString("SjCreatedSuccesfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travaux de sauvegarde supprimés :.
        /// </summary>
        internal static string SjDelSuccesfully {
            get {
                return ResourceManager.GetString("SjDelSuccesfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le travail de sauvegarde s&apos;est déroulé sans encombre.
        /// </summary>
        internal static string SjExecSuccesfully {
            get {
                return ResourceManager.GetString("SjExecSuccesfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exec-SaveJob : est appelé avec les arguments de commande :.
        /// </summary>
        internal static string SjExecWith {
            get {
                return ResourceManager.GetString("SjExecWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le travail demandé n&apos;existe pas (.
        /// </summary>
        internal static string SjNotExist {
            get {
                return ResourceManager.GetString("SjNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source :.
        /// </summary>
        internal static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le répertoire source n&apos;existe pas.
        /// </summary>
        internal static string SrcDirNotExists {
            get {
                return ResourceManager.GetString("SrcDirNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trop d&apos;identifiants ont été passés sans bénéficier de séparateurs :.
        /// </summary>
        internal static string TooMuchIdWithoutSep {
            get {
                return ResourceManager.GetString("TooMuchIdWithoutSep", resourceCulture);
            }
        }
    }
}
