//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Config.i18n.Ressources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources_fr {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_fr() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Job.Config.i18n.Resources.Resources.fr", typeof(Resources_fr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajouter une application métier.
        /// </summary>
        internal static string AddBusinessAppWatermark {
            get {
                return ResourceManager.GetString("AddBusinessAppWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajouter.
        /// </summary>
        internal static string AddButton {
            get {
                return ResourceManager.GetString("AddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajouter un type de fichier.
        /// </summary>
        internal static string AddFileTypeWatermark {
            get {
                return ResourceManager.GetString("AddFileTypeWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mauvais arguments, Add-Savejob &lt;nom&gt; &lt;source&gt; &lt;destination&gt; &lt;type&gt;.
        /// </summary>
        internal static string AddSjBadArgs {
            get {
                return ResourceManager.GetString("AddSjBadArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  les types possibles sont : full, diff.
        /// </summary>
        internal static string AddSJBadType {
            get {
                return ResourceManager.GetString("AddSJBadType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mauvais arguments donnés :.
        /// </summary>
        internal static string BadArgsGiven {
            get {
                return ResourceManager.GetString("BadArgsGiven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parcourir....
        /// </summary>
        internal static string BrowseButton {
            get {
                return ResourceManager.GetString("BrowseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applications métiers bloquant SJ.
        /// </summary>
        internal static string BusinessAppBlockingTitle {
            get {
                return ResourceManager.GetString("BusinessAppBlockingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to est appelé avec les arguments : .
        /// </summary>
        internal static string CallWithArgs {
            get {
                return ResourceManager.GetString("CallWithArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmer.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créé le : .
        /// </summary>
        internal static string Created {
            get {
                return ResourceManager.GetString("Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mauvais arguments fournis, la commande se formule comme suivant : Delete-SaveJob &lt;id&gt;.
        /// </summary>
        internal static string DelSjBadArgs {
            get {
                return ResourceManager.GetString("DelSjBadArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete-SaveJob : est appelé avec les arguments :.
        /// </summary>
        internal static string DelSjCallWithArgs {
            get {
                return ResourceManager.GetString("DelSjCallWithArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination :.
        /// </summary>
        internal static string Destination {
            get {
                return ResourceManager.GetString("Destination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dossier de destination.
        /// </summary>
        internal static string DestPath {
            get {
                return ResourceManager.GetString("DestPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Différentielle.
        /// </summary>
        internal static string Differential {
            get {
                return ResourceManager.GetString("Differential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le répertoire destination n&apos;existe pas.
        /// </summary>
        internal static string DstDirNotExist {
            get {
                return ResourceManager.GetString("DstDirNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrer la clé de chiffrement.
        /// </summary>
        internal static string EnterEncryptionKeyWatermark {
            get {
                return ResourceManager.GetString("EnterEncryptionKeyWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mauvais arguments, la commande nécessite Exec-Savejob &lt;id&gt;|&lt;nom&gt; ou &lt;id&gt;;&lt;id&gt;;&lt;id&gt; ou &lt;id&gt;,&lt;id&gt; .
        /// </summary>
        internal static string ExecSjBadArgs {
            get {
                return ResourceManager.GetString("ExecSjBadArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Types de fichiers à chiffrer.
        /// </summary>
        internal static string FileTypesToEncryptTitle {
            get {
                return ResourceManager.GetString("FileTypesToEncryptTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complet.
        /// </summary>
        internal static string Full {
            get {
                return ResourceManager.GetString("Full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id : .
        /// </summary>
        internal static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;id doit être un nombre .
        /// </summary>
        internal static string IdShouldBeANumber {
            get {
                return ResourceManager.GetString("IdShouldBeANumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type indisponible : .
        /// </summary>
        internal static string InvalidType {
            get {
                return ResourceManager.GetString("InvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mauvais arguments fournis : .
        /// </summary>
        internal static string LanguageBadArgs {
            get {
                return ResourceManager.GetString("LanguageBadArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Langue modifiée au profit de la nouvelle langue : .
        /// </summary>
        internal static string LanguageChanged {
            get {
                return ResourceManager.GetString("LanguageChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to n&apos;est pas un language supporté par le système.
        /// </summary>
        internal static string LanguageNotSupported {
            get {
                return ResourceManager.GetString("LanguageNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dernière exécution.
        /// </summary>
        internal static string LastExecution {
            get {
                return ResourceManager.GetString("LastExecution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dernière sauvegarde : .
        /// </summary>
        internal static string LastSave {
            get {
                return ResourceManager.GetString("LastSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List-SaveJob : est appelé avec les arguments : .
        /// </summary>
        internal static string ListSjCallWith {
            get {
                return ResourceManager.GetString("ListSjCallWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mauvais arguments, la commande nécessite Set-LogPath &lt;logPath&gt;.
        /// </summary>
        internal static string LogPathBadArgs {
            get {
                return ResourceManager.GetString("LogPathBadArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogPath a été mis à jour : .
        /// </summary>
        internal static string LogPathUpdatedSuccesfully {
            get {
                return ResourceManager.GetString("LogPathUpdatedSuccesfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arguments manquants :.
        /// </summary>
        internal static string MissingArgs {
            get {
                return ResourceManager.GetString("MissingArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom .
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il n&apos;y a aucun travail de sauvegarde à imprimer.
        /// </summary>
        internal static string NoSjToPrint {
            get {
                return ResourceManager.GetString("NoSjToPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to n&apos;est pas un chemin valide.
        /// </summary>
        internal static string NotValidPath {
            get {
                return ResourceManager.GetString("NotValidPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supprimer la sélection.
        /// </summary>
        internal static string RemoveSelectedButton {
            get {
                return ResourceManager.GetString("RemoveSelectedButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Réinitialiser.
        /// </summary>
        internal static string ResetButton {
            get {
                return ResourceManager.GetString("ResetButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un travail de sauvegarde existe déjà sous ce nom.
        /// </summary>
        internal static string SaveAlreadyExist {
            get {
                return ResourceManager.GetString("SaveAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sélectionner la langue.
        /// </summary>
        internal static string SelectLanguagePlaceholder {
            get {
                return ResourceManager.GetString("SelectLanguagePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sélectionner la langue.
        /// </summary>
        internal static string SelectLanguageTitle {
            get {
                return ResourceManager.GetString("SelectLanguageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sélectionner le type de log.
        /// </summary>
        internal static string SelectLogTypePlaceholder {
            get {
                return ResourceManager.GetString("SelectLogTypePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sélectionner le type de log.
        /// </summary>
        internal static string SelectLogTypeTitle {
            get {
                return ResourceManager.GetString("SelectLogTypeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sélectionner le type de sauvegarde.
        /// </summary>
        internal static string SelectSaveType {
            get {
                return ResourceManager.GetString("SelectSaveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les séparateurs sont inconnus du système : .
        /// </summary>
        internal static string SeparatorNotReco {
            get {
                return ResourceManager.GetString("SeparatorNotReco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Définir la clé de chiffrement.
        /// </summary>
        internal static string SetEncryptionKeyTitle {
            get {
                return ResourceManager.GetString("SetEncryptionKeyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set-LogPath : est appelé avec les arguments : .
        /// </summary>
        internal static string SetLogPathCallWith {
            get {
                return ResourceManager.GetString("SetLogPathCallWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Définir le chemin du log.
        /// </summary>
        internal static string SetLogPathTitle {
            get {
                return ResourceManager.GetString("SetLogPathTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Définir le chemin du log.
        /// </summary>
        internal static string SetLogPathWatermark {
            get {
                return ResourceManager.GetString("SetLogPathWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paramètres.
        /// </summary>
        internal static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le nouveau travail de sauvegarde a été sauvegardé.
        /// </summary>
        internal static string SjCreatedSuccesfully {
            get {
                return ResourceManager.GetString("SjCreatedSuccesfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travaux de sauvegarde supprimés :.
        /// </summary>
        internal static string SjDelSuccesfully {
            get {
                return ResourceManager.GetString("SjDelSuccesfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le travail de sauvegarde s&apos;est déroulé sans encombre.
        /// </summary>
        internal static string SjExecSuccesfully {
            get {
                return ResourceManager.GetString("SjExecSuccesfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exec-SaveJob : est appelé avec les arguments de commande :.
        /// </summary>
        internal static string SjExecWith {
            get {
                return ResourceManager.GetString("SjExecWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le travail demandé n&apos;existe pas (.
        /// </summary>
        internal static string SjNotExist {
            get {
                return ResourceManager.GetString("SjNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source :.
        /// </summary>
        internal static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le répertoire source n&apos;existe pas.
        /// </summary>
        internal static string SrcDirNotExists {
            get {
                return ResourceManager.GetString("SrcDirNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dossier source.
        /// </summary>
        internal static string SrcPath {
            get {
                return ResourceManager.GetString("SrcPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trop d&apos;identifiants ont été passés sans bénéficier de séparateurs :.
        /// </summary>
        internal static string TooMuchIdWithoutSep {
            get {
                return ResourceManager.GetString("TooMuchIdWithoutSep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mettre à jour la clé.
        /// </summary>
        internal static string UpdateKeyButton {
            get {
                return ResourceManager.GetString("UpdateKeyButton", resourceCulture);
            }
        }
    }
}
