name: EASYSave Pipeline

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Docker Compose
        run: sudo apt-get update && sudo apt-get install -y docker-compose

      - name: Run tests
        run: sudo chmod +x ./launch_test.sh && ./launch_test.sh

  docker-buildx-ubuntu-arm-amd-windows-amd:
    runs-on: ubuntu-latest
    needs: test
    steps:
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2

        - name: Login to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_TOKEN }}

        - name: Build and push multi-platform image
          uses: docker/build-push-action@v4
          with:
            file: Dockerfile
            platforms: linux/amd64,linux/arm64,windows/amd64
            push: true
            tags: n0ianoba/a3_genie_logiciel:latest